<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Lidar properties -->
    <xacro:property name="lidar_mass" value="0.17"/>
    <xacro:property name="lidar_radius" value="0.02"/>
    <xacro:property name="lidar_height" value="0.02"/>
    
    <!-- Lidar sensor parameters -->
    <xacro:property name="lidar_samples" value="360"/>
    <xacro:property name="lidar_frequency" value="10"/>
    <xacro:property name="lidar_min_angle" value="-3.14159"/>
    <xacro:property name="lidar_max_angle" value="3.14159"/>
    <xacro:property name="lidar_min_range" value="0.12"/>
    <xacro:property name="lidar_max_range" value="12.0"/>

    <!-- Lidar Link -->
    <link name="lidar_link">
        <inertial>
            <mass value="${lidar_mass}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
            </geometry>
            <material name="black">
                <color rgba="0.1 0.1 0.1 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- Joint attaching lidar to trunk (mounted on top) -->
    <joint name="lidar_joint" type="fixed">
        <parent link="trunk"/>
        <child link="lidar_link"/>
        <!-- Positioned on top of the trunk, centered -->
        <origin xyz="0.22 0.0 ${trunk_height/2.0 + lidar_height/2.0 + 0.031}" rpy="0 0 0"/>
    </joint>

    <!-- =========================================== -->
    <!-- GAZEBO LIDAR SENSOR - Gazebo Harmonic       -->
    <!-- =========================================== -->
    
    <gazebo reference="lidar_link">
        <material>
            <ambient>0.1 0.1 0.1 1</ambient>
            <diffuse>0.1 0.1 0.1 1</diffuse>
        </material>
        
        <!-- GPU Lidar Sensor for Gazebo Harmonic -->
        <sensor name="lidar_sensor" type="gpu_lidar">
            <pose>0 0 0 0 0 0</pose>
            <always_on>true</always_on>
            <update_rate>${lidar_frequency}</update_rate>
            <visualize>true</visualize>
            <topic>scan</topic>
            <gz_frame_id>lidar_link</gz_frame_id>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>${lidar_samples}</samples>
                        <resolution>1</resolution>
                        <min_angle>${lidar_min_angle}</min_angle>
                        <max_angle>${lidar_max_angle}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>${lidar_min_range}</min>
                    <max>${lidar_max_range}</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </lidar>
        </sensor>
    </gazebo>

</robot>
